# Generated by Django 4.0.6 on 2022-09-08 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('portrait', models.ImageField(blank=True, upload_to='media')),
                ('years', models.CharField(blank=True, max_length=75)),
                ('about', models.TextField(blank=True, max_length=750)),
                ('slug', models.SlugField(default='', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, upload_to='media')),
                ('book_view', models.ImageField(blank=True, upload_to='media')),
                ('book_view1', models.ImageField(blank=True, upload_to='media')),
                ('book_view2', models.ImageField(blank=True, upload_to='media')),
                ('name', models.CharField(max_length=100)),
                ('read', models.URLField(blank=True, max_length=1000)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='', max_length=75)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='magazine.author')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('slug', models.SlugField(default='', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Commet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='magazine.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='magazine.genres'),
        ),
    ]
