# Generated by Django 4.0.6 on 2022-07-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='magaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=32)),
                ('data_create', models.CharField(max_length=10)),
            ],
        ),
    ]
