# Generated by Django 4.0.6 on 2022-07-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magaz',
            name='poster',
            field=models.ImageField(default=1, upload_to='static/media/'),
            preserve_default=False,
        ),
    ]
