# Generated by Django 4.0.6 on 2022-09-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commet',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
