# Generated by Django 4.0.6 on 2022-09-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_commet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commet',
            name='image',
        ),
    ]
