# Generated by Django 4.0.6 on 2022-08-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_commet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
    ]
