# Generated by Django 4.0.6 on 2022-08-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
