# Generated by Django 4.0.6 on 2022-08-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0010_remove_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.SlugField(default='', max_length=75),
        ),
    ]
