# Generated by Django 4.0.5 on 2022-08-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0013_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_view',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', max_length=75),
        ),
    ]
