# Generated by Django 4.0.5 on 2022-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0014_book_book_view_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_view1',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_view2',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
