# Generated by Django 4.0.6 on 2022-08-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0016_author_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='commet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.commet', verbose_name='Родитель'),
        ),
    ]
