# Generated by Django 4.0.6 on 2022-08-25 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0017_commet_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commet',
            name='parent',
        ),
        migrations.AddField(
            model_name='commet',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
