# Generated by Django 4.0.6 on 2022-08-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0020_alter_commet_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commet',
            name='create_at',
            field=models.DateTimeField(default=-10800),
        ),
    ]
