# Generated by Django 4.0.6 on 2022-08-25 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0021_alter_commet_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commet',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
