# Generated by Django 4.0.6 on 2022-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0022_alter_commet_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='book', to='magazine.genres'),
        ),
    ]
