# Generated by Django 4.0.6 on 2022-08-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0028_alter_commet_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commet',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='magazine.book'),
        ),
    ]
