# Generated by Django 4.0.6 on 2022-08-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0031_alter_commet_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='commet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.commet', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='commet',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commet', to='magazine.book'),
        ),
    ]
