# Generated by Django 4.0.6 on 2022-08-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0032_commet_parent_alter_commet_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commet',
            name='parent',
        ),
        migrations.AlterField(
            model_name='commet',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='magazine.book'),
        ),
    ]
