# Generated by Django 4.0.6 on 2022-08-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0033_remove_commet_parent_alter_commet_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AlterField(
            model_name='book',
            name='poster',
            field=models.ImageField(blank=True, upload_to='media/img'),
        ),
    ]
