# Generated by Django 4.0.6 on 2022-08-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0035_author_about_author_portrait_author_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', max_length=75),
        ),
    ]
