# Generated by Django 4.0.6 on 2022-08-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0037_alter_author_about_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='portrait',
            field=models.ImageField(upload_to='media'),
        ),
    ]
